version: "3.8" # especifica la versión de Docker Compose

services:
  mongodb:
    image: "mongo:latest" # última imagen de MongoDB
    container_name: "mongodb_container"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser # usuario root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword # contraseña del usuario root
      - MONGO_INITDB_DATABASE=mi-database # nombre de la base de datos a crear inicialmente
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - "mongodata:/data/db" # monta el volumen para persistencia de datos
    ports:
      - "27018:27017" # cambia el puerto mapeado al puerto 2204 de tu máquina host

volumes:
  mongodata: # define el volumen para datos de MongoDB
